# FireHub Project Funding Configuration
# For GitHub display on the repository page under "Sponsor"

github: 
  - The-FireHub-Project

open_collective: 
  - firehub

paypal: 
  - danijel.galic@outlook.com
