name: test Bug Report
description: Report a bug in Core, Adapters, or Modules
title: "[Bug] : "
type: Bug
labels: ["type: Bug", "status: Waiting Triage"]

body:

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which part of FireHub is affected?
      options:
        - Core Standard
        - Core Professional
        - Core Enterprise
        - HTTP Adapter
        - Console Adapter
        - Capability Module
        - Adapter Module
        - ...other platform
    validations:
      required: true

  - type: input
    id: platform-version
    attributes:
      label: Platform version
      placeholder: "example: Professional v1.0.0"
    validations:
      required: true
